name:                signe
version:             0.1.0.0
github:              "NicklasBoto/signe"
license:             BSD3
author:              "Nicklas Botö"
maintainer:          "git@nicbot.xyz"
copyright:           "GPL-3"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/NicklasBoto/signe#readme>

build-tools:
- alex
- happy

dependencies:
- base >= 4.7 && < 5
- array

library:
  source-dirs: src

executables:
  signe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - signe

tests:
  signe-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - signe
